[tool.poetry]
name = "JKCommentCrawler"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
ndgr-client = { git = "https://github.com/tsukumijima/NDGRClient", rev = "e8462e12f99a25047a6a456accd434d3fc8d7ce8" }

[tool.poetry.group.dev.dependencies]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
