[tool.poetry]
name = "JKCommentCrawler"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
ndgr-client = { git = "https://github.com/tsukumijima/NDGRClient", rev = "1e7c4398a51b02ffd35d4b93ba98449a89f63c81" }

[tool.poetry.group.dev.dependencies]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
