[tool.poetry]
name = "JKCommentCrawler"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
ndgr-client = { git = "https://github.com/tsukumijima/NDGRClient", rev = "063eadbfae341125ed1adae5ef8afb51c692dd47" }

[tool.poetry.group.dev.dependencies]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
